[theme]
primaryColor = "#9B1C31"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#14213D"
font = "sans-serif"

[server]
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = "type"
